### PR TITLE
Use pubsub module for handling multiple instances.

### PR DESCRIPTION
**Pull request by yariplus**
Fixes errors on clustered forums.
Allows reload instead of restart.

This fixes the errors with clusters, but requires Redis. This shouldn't be an issue since clustered servers should always have Redis. Regular forums will operate as normal.

### CODE REVIEW

**Comment by exomarty** [comment]
Thanks ;) why closed?

**Comment by yariplus** [comment]
I found a few problems with it. I'll reopen when I find a fix.

**Comment by yariplus** [comment]
Okay, I think it should work good now. I tested it on 1.0.0 with clustering and without clustering.

**Comment by exomarty** [comment]
Good work :D

**Comment by exomarty** [comment]
Probably an admin here should aprobe as i have no power on the repo after transfer it :)

**Comment by yariplus** [comment]
Okay, you should be admin now on this repo.

**Pull request merged**
