### PR TITLE
Adaption of user and setup interfaces

### PR DESCRIPTION
**Pull request by wellenreiter01**
I have changed the admin/setup to be able to select a room where the bot announces news on new topics or posts in selected categories. 
This is similar to the nodebb-plugin-discord modules interface now.
Moved the user setting directly into the users settings page
Adapted REAME.md to the enhanced setup

### CODE REVIEW

**Comment by exomarty** [comment]
This is an amazing g job and a way to go with the plugin bot. 
Very happy for this inprovement. 
I have some questions. 
I see you say i have to add the bot to a room. Will I be able to have private conversation with the bot like always?
Can we have an easy way for users to get the room id and well explained into the user settings?

**Comment by wellenreiter01** [comment]
All communication with the bot works, like read/reply to posts works in private chat only. The room is used for announcements of new posts or topics in the selected categories.
If a user sends a command from the room to the bot, the bot will reply in the private chat only.
I  didn't find a way to get the room ID where the command comes from and also I think actions like posting/reading would spam the room and may violence the users privacy.

> Can we have an easy way for users to get the room id and well explained into the user settings?

I didn't figure out, how templates can be pushed into the user settings. With a template added to the user settings page we could setup a help with translations displayed in the user settings.

Displaying just the room id and a one sentence explanation in English should be possible in any case.

My idea was ,that the communities move to chat platforms like discord and telegram more and more, and the the plugin will use the general room on telegram, where all users are connected anyway. Therefore the room id wouldn't need to be known by the nodebb user.

**Comment by exomarty** [comment]
Ok. I understand a little more now the room thing and sounds good. 
 
The main purpose of the plugin was to get notifications from nodebb in private ( mentions, private messages, quotes ) 
Is that working too?

Can you add a further explanation in users sertings in english while we figure out the translations thing. 

Thank you.

**Comment by wellenreiter01** [comment]
>  The main purpose of the plugin was to get notifications from nodebb in private ( mentions, private messages, quotes )
>  Is that working too?

The notifications are only implemented for new topics or new posts in one or more categories, which can be configured on the admin pages.
Notifications for mentions, private messages and quotes where not implemented, and I didn't extend the functionality of the plugin ,as the current implementation is sufficient for me.
I will add an explanation line to the user settings and send a new pull request today or tomorrow

**Comment by exomarty** [comment]
Thank you. I will merge it for now. 
I wont be able to push it to npm until 2 weeks due to travel.

**Pull request merged**
